<link rel="stylesheet" href="<?php echo base_url(); ?>assets/css/package.css" >
<div class="container">   
    <div class="row"> 
        <p> Welcome to pennybanker.com.("Pennybanker.com"). These Terms and Conditions apply to the Pennybanker.com Services located at pennybanker.com, our paid content, and our online discussion forums, as well as any other of our websites, digital services or mobile or other applications on which a link to these Terms and Conditions appears (collectively, the "Pennybanker.com Services"), all of which Pennybanker.com Services are provided by Pennybanker.com at any time and from time to time in its sole discretion. Pennybanker.com does not control, and is not responsible for, any third-party site to which the Pennybanker.com Services link or that links to any Pennybanker.com Services. </p>
<p> You agree that your use of the Pennybanker.com Services is subject to the following Terms and Conditions. If you do not agree with the Terms and Conditions in their entirety, please do not use any Pennybanker.com Services. These Terms and Conditions may be modified at any time and from time to time; the date of the most recent changes or revisions will appear on this page. Continued access to the Pennybanker.com Services by you will constitute your acceptance of any changes or revisions to these Terms and Conditions. Portions of the Pennybanker.com Services may be governed by different or additional terms and conditions. In the event of a conflict between any provision of these Terms and Conditions, on the one hand, and any other terms and conditions, on the other hand, the applicable provision of these Terms and Conditions shall prevail with respect to your use of the Pennybanker.com Services. </p>
<p> The materials and tools contained on the Pennybanker.com Services are provided by Pennybanker.com as a service to you for your noncommercial, personal use on an "as is, as available" basis and may be used by you for informational purposes only. You acknowledge that you are using the Pennybanker.com Services at your own risk. Pennybanker.com assumes no responsibility for errors or omissions in these materials. Pennybanker.com makes no commitment to update the information contained herein. Pennybanker.com makes no, and expressly disclaims any and all, representations or warranties, express or implied, regarding the Pennybanker.com Services, including without limitation the accuracy, completeness, or reliability of text, graphics, links, products and services, and other items accessed from or via the Pennybanker.com Services, or that use of the Pennybanker.com Services will be uninterrupted, error-free, or free of viruses or other harmful components. No advice or information given by Pennybanker.com or any other party on the Pennybanker.com Services shall create any warranty or liability. The content provided through Pennybanker.com Services should be used for informational purposes only; the content is not intended to be a substitute for professional advice. Always seek the advice of a relevant professional with any questions about any health, financial or other decision you are seeking to make. In the case of our product reviews, consumers should always consult the manufacturer and/or their dealer/distributor for the most up-to-date product information, features and specifications. </p>
<p> Pennybanker.com does not warrant or make any representations regarding the use or the results of the use of the materials on the Pennybanker.com Services in terms of their correctness, accuracy, timeliness, reliability, or otherwise. Under no circumstances shall Pennybanker.com or any of its parents, subsidiaries, affiliates, licensors, or their respective partners, officers, directors, employees, or agents be held liable for any damages, whether direct, incidental, indirect, special, or consequential, and including, without limitation, lost revenues or lost profits, arising from or in connection with your use, reliance on, or performance of the information on the Pennybanker.com Services. Your sole remedy in the event of any deficiency, defect, failure, error or interruption in the Pennybanker.com Services or any goods or services offered for sale through the Pennybanker.com Services shall be to request that Pennybanker.com correct the matter or, if Pennybanker.com fails to do so, to discontinue use of the Pennybanker.com Services. In no event shall Pennybanker.com’s liability exceed an amount equal to all fees paid by you to Pennybanker.com in connection with your use of the Pennybanker.com Services. </p>
<p> Pennybanker.com periodically schedules system downtime for maintenance and other purposes. Unplanned outages also may occur. Pennybanker.com shall have no liability for the resulting unavailability of the Pennybanker.com Services or for any loss of data or transactions caused by planned or unplanned system outages, or any outages of web host providers or the Internet infrastructure and network external to the Pennybanker.com Services. </p>
<h3> Copyright</h3>
<p> All materials published on or in the Pennybanker.com Services are protected by copyright laws, and may not be reproduced, republished, distributed, transmitted, resold, displayed, broadcast, or otherwise exploited in any manner without the express written permission of either Pennybanker.com or, in the case of content licensed by Pennybanker.com from third parties, the entity that is credited as the copyright holder of such licensed content. You may download freely accessible material (one copy per page) from this Pennybanker.com Services for your personal and noncommercial use only, without altering or removing any trademark, copyright, or other notice from such material; you must pay a fee to access that content which requires a fee for access. To request use of Pennybanker.com Services content – other than personal, non-commercial use as described above – contact info@pennybanker.com to request specific, written authorization, which may require payment of a fee and may be granted or denied in the sole discretion of Pennybanker.com. </p>
<p> In the event you believe that any content posted on the Pennybanker.com Services infringes your copyright or other intellectual-property rights, you may notify Pennybanker.com by providing the information required by the Online Copyright Infringement Liability Limitation Action of the Digital Millennium Copyright Act, 17 U.S.C. 512. </p>



<h3> User Generated Content</h3>
<p> Pennybanker.com, through its forums or otherwise, may provide users an opportunity to transmit or post content, which may include text, videos, photographs, images, sound files and/or other content, to the Pennybanker.com Services (collectively, "User Content") and may provide for the hosting, sharing and/or publishing of such User Content. Pennybanker.com does not necessarily endorse, support, sanction, encourage, or agree with User Content and expressly disclaims any and all liability in connection with any User Content. </p>
<p> You shall not transmit or post any User Content that: (a) is unlawful, threatening, harassing, abusive, false, inaccurate, deceptive, misleading, offensive, distasteful, inappropriate, libelous, defamatory, obscene, vulgar, pornographic, profane, indecent, invasive of another’s privacy or harmful to minors in any way; (b) constitutes or encourages conduct that would constitute a criminal offense, give rise to civil liability, or otherwise violate any local, state, national, or international law; (c) is copyrighted, protected by trade secret, patent, trademark or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to submit or post the material and to grant Pennybanker.com all of the license rights granted herein; (d) refers derisively to the goods or services of others; (e) includes any disruptive elements that may damage or interfere with the Pennybanker.com Services such as computer viruses, bots, worms, bombs, or Trojan horses; (f) includes advertisements or solicitations of business; (g) impersonates another person; (h) includes any person’s full name or personal or identifying information without that person’s authorization; (i) violates the law or otherwise violates these Terms of Service; or (j) provides a link to any of the above. </p>
<p> In connection with any User Content that you submit, you affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use, and to authorize Pennybanker.com to use, all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Content to enable inclusion and use of the User Content in the manner contemplated by the Pennybanker.com Services and these Terms and Conditions; (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Content to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Content in the manner contemplated by the Pennybanker.com Services and these Terms and Conditions; and (iii) it complies with these Terms and Conditions. </p>
<p> You understand that all User Content is the sole responsibility of the person who transmits or posts that User Content. This means that you, and not Pennybanker.com, are entirely and solely responsible for all User Content that you transmit or post and for the consequences of Pennybanker.com publishing such User Content. Pennybanker.com does not and cannot review the User Content transmitted or posted by users and is not responsible for such content. However, Pennybanker.com shall have the right, but not the obligation, to refuse, delete, move, remove, or edit any User Content that violates these Terms and Conditions or is otherwise objectionable, as determined by Pennybanker.com in its sole discretion and without notice. Any specific complaints regarding User Content must be directed to legal@Pennybanker.com, and any promise by Pennybanker.com to investigate, delete, remove, or otherwise edit any User Content shall be non-binding unless expressly provided in writing by a Vice President of Pennybanker.com. </p>
<p> You agree to indemnify Pennybanker.com and its parents, subsidiaries, and affiliates, and each of their respective partners, officers, directors, employees, agents and representatives, against, and to hold each of them harmless from, any and all claims and liabilities (including attorney’s fees) that may arise from your use of the Pennybanker.com Services, your transmission or posting of User Content, your unauthorized use of material obtained from the Pennybanker.com Services, your breach of these Terms and Conditions, your violation of any law, regulation or any right of any other person or entity, and any unauthorized use of your account or password. Pennybanker.com reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting our defense of such matter. </p>
<p> Pennybanker.com does not claim any ownership rights in the User Content. By transmitting or posting User Content, you grant to Pennybanker.com the perpetual, non-terminable, worldwide, nonexclusive, royalty-free, sublicenseable and transferable right and license to use, reproduce, edit, remove, modify (including the size and aspect ratio of photographs), publish, transmit, display, distribute, have distributed, promote, perform, and prepare derivative works of, all or any potion of such User Content in any form, in any medium now existing or hereinafter invented for any purpose, including commercial uses, including without limitation, in connection with the Pennybanker.com Services, in connection with other Pennybanker.com publications, in connection with Pennybanker.com’s (and our successors’) business, in connection with promoting and redistributing part or all of the Pennybanker.com Services (and derivative works thereof) without additional notice, approval, consent, compensation or attribution, or in connection with stories featuring the Pennybanker.com Services or any content on the Pennybanker.com Services in other news and media websites or other outlets. You waive any moral rights you may have in the User Content. You also grant each user of the Pennybanker.com Services a non-exclusive license to access your User Content through the Pennybanker.com Services, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Content as permitted through the functionality of the Pennybanker.com Services and under these Terms and Conditions. </p>
<h3> Beta Testing</h3>
<p> From time to time, users of certain portions of the Pennybanker.com Services may be given the opportunity to volunteer to become part of a group of "Beta Testers". Beta Testers will review, test and provide written and/or verbal Feedback on new ideas and features for Pennybanker.com Services. If you volunteer to be a Beta Tester, you agree (i) that all concepts, design mockups, content or other information shared with you as a Beta Tester is confidential information of Pennybanker.com and that you will keep it confidential, use it only in connection with your role as a Beta Tester, and not disclose it to any other person, and (ii) that Pennybanker.com will be the sole owner of all right, title and interest in and to any Feedback you provide to Pennybanker.com in connection with your role as a Beta Tester. For purposes hereof, "Feedback" means any comments, suggestions, expectations, test results, error data, bug reports or other information or materials that you provide to Pennybanker.com in connection with your role as a Beta Tester. </p>
<b> Subscriptions</b>
<p> Subscriptions to Pennybanker.com College Compass and Pennybanker.com Graduate School Compass (collectively, "Compass") are available at Pennybanker.com. Such subscriptions may include access to the electronic edition of a Pennybanker.com guidebook. If you purchase a one-year subscription to Compass through Pennybanker.com, you may request a refund within 24 hours of purchase. Please send an email to info@pennybanker.com. Refund requests will not be honored unless submitted within 24 hours of purchase. </p>
<b> Third Party Provider Content Notices</b>

<p> By accessing the Pennybanker.com Services (including without limitation, any digital service or application made available by Pennybanker.com), you specifically acknowledge and agree that: (a) Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistributed directly or indirectly in any medium; (b) no Associated Press materials nor any portion thereof may be stored in a computer except for personal and non-commercial use; (c) the Associated Press will not be liable for any delays, inaccuracies, errors or omissions in any Associated Press materials or in the transmission or delivery of any part thereof or for any damages arising therefrom or occasioned thereby; (d) the Associated Press is an intended third party beneficiary of these terms and conditions and it may exercise all rights and remedies available to it; and (e) the Associated Press reserves the right to audit your use of Associated Press materials or any portion thereof at any time. </p>
<b> Paid Content</b>

<p> Purchasers of paid content are not permitted to share, distribute, sell, or otherwise transfer their password to other individuals. The password is for the purchaser's sole use. Significant or unusual use of a single password (including but not limited to significant use of a single password on multiple computers or devices) could result in suspension of that password. Paid content is protected by copyright laws, and may not be transmitted (whether by e-mail or otherwise), reproduced, republished, distributed, resold, displayed, broadcast, or otherwise exploited in any manner without the express written permission of Pennybanker.com. </p>
<b> Featured Services</b>

<p> Pennybanker.com is committed to providing visitors to the Pennybanker.com Services with as many features as possible, some of which may be provided by third parties. The companies that Pennybanker.com selects as featured service providers offer products and services that site visitors may find useful. Pennybanker.com in certain cases may have a business relationship with certain third parties that it selects as a featured service provider. Pennybanker.com is not responsible for the accuracy or reliability of any advice or information given, or of any statement made, by the companies providing featured services, or for the content, services, products, or advertising on or available from their websites, or for the availability and operations of their websites. </p>
<b> Jurisdiction</b>

<p> You agree that any claim, action, or proceeding arising out of these Terms and Conditions, or your use of the Pennybanker.com Services, shall be governed by and construed in accordance with the laws of the State of New York applicable to contracts to be wholly performed therein, and any action based on or alleging a breach of this Agreement must be brought in a state or federal court located in New York County, New York. In addition, you agree to submit to the personal jurisdiction of such courts. </p>

    </div>
</div>